[package]
name = "winimage-magic"
version = "0.1.1"
edition = "2024"

[dependencies]
image = "0.25.6"
clap = { version = "4.5.40", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
winreg = "0.55.0"

[build-dependencies]
winresource = "0.1.22"
